## BAI TAP 3.1 - 3.9 GIAO TRINH 


In [37]:
import numpy as np

In [ ]:
#3.1 
import numpy as np 
np.__version__ 


In [ ]:
#3.2 
#1
mang=[0,1,2,3,4,5,6,7,8,9]
arr1 = np.array(mang)
print (arr1)
print (arr1.itemsize)
print (arr1.dtype)
#2
arr_odd=arr1.copy()
arr_even=arr1.copy()
print (arr_odd)
print (arr_even)
#3 
arr_update_1=arr1.copy()
for i in range (len(arr_update_1)):
    if arr_update_1[i]%2 ==0 :
        arr_update_1[i]=100

print (arr_update_1)



In [ ]:
#3.3
#1
arr_a = np.array([1,2,3,2,3,4,3,4,5,6])
arr_b = np.array([7,2,10,2,7,4,9,4,9,8])
arr_c=np.array([])
arr_d=np.array([])
for i in arr_a:
    if i in arr_b:
        arr_c=np.append(arr_c,i)   
print (arr_c)


#2
for i in arr_a:
    if  i not in arr_b:
        arr_d=np.append(arr_d,i)
print (arr_d)
#3
arr_e=np.array([2,6,1,9,10,3,27,8,6,25,16])
arr_f=np.array([])
k=[5,6,7,8,9,10]
for i in arr_e:
    if i in k:
        arr_f=np.append(arr_f,i)
print (arr_f)


In [ ]:
#3.4
#1
arr_zeros = np.zeros(10)
arr_zeros[4]=1
arr_zeros
#2
arr_h=np.array([i for i in range (10,25)])
print (np.sort(arr_h)[::-1])
#3
arr_k=np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l=np.array([])
for i in arr_k:
   if i !=0:
      arr_l=np.append(arr_l,i)
print (arr_l)
#4
arr_l=np.append(arr_l,10)
arr_l=np.append(arr_l,20)
print (arr_l)
#5
arr_l=np.insert(arr_l,5,100)
print (arr_l)
#6
arr_l=np.delete(arr_l,0)
arr_l=np.delete(arr_l,0)
arr_l=np.delete(arr_l,0)
arr_l



In [93]:
#3.6
#1
arr=np.full((3,3),True,bool)
arr
#2
arr_ID=np.array([0,1,2,3,4,5,6,7,8])
arr_ID2=arr_ID.reshape((3,3))
print (arr_ID2)
#3
arr_ID2[:,[0,2]]=arr_ID2[:,[2,0]] 
print (arr_ID2)
#4
arr_ID2[[0,1],:]=arr_ID2[[1,0],:] 
print (arr_ID2)
#5
print (arr_ID2[::-1])
print (arr_ID2[:,::-1])




[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
[[5 4 3]
 [2 1 0]
 [8 7 6]]
[[8 7 6]
 [2 1 0]
 [5 4 3]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
